version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: snowflake
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data_new:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  bot:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: root
      DB_PASSWORD: "root"
      DB_NAME: snowflake
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  db_data_new: 